{% set name = "commonregex" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://raw.githubusercontent.com/madisonmay/CommonRegex/master/dist/commonregex-{{ version }}.tar.gz
  sha256: 08e93aec3ce2a3ae29d89cc249af47e70df10218f2161455b3df19fb5cb67d00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - commonregex
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: http://www.github.com/madisonmay/CommonRegex
  license: MIT
  summary: 'Find all dates, times, emails, phone numbers, links, emails, ip addresses, prices, bitcoin address, and street addresses in a string.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
